### ISSUE TITLE
Mac wheel is partially broken

### ISSUE THREAD

**Issue by pfreixes** [pfreixes/acsylla#33]
The current Mac wheel makes the compilation by linking the OpenSSL library to a specific version, notice the usage of `/usr/local/opt/openssl/lib/libssl.1.0.0.dylib`.

```bash
$ otool -L /Users/xxxx/personal/sandbox/lib/python3.8/site-packages/acsylla/_cython/cyacsylla.cpython-38-darwin.so
/Users/xxxx/personal/sandbox/lib/python3.8/site-packages/acsylla/_cython/cyacsylla.cpython-38-darwin.so:
	/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/openssl/lib/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/libuv/lib/libuv.1.dylib (compatibility version 2.0.0, current version 2.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 902.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
```

Once compiled the library that should be used must be at least the one with the minor version otherwise systems with a patched release won't work, as can be seen in the following snippet

```python
>>> import acsylla
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/xxxx/personal/sandbox/lib/python3.8/site-packages/acsylla/__init__.py", line 1, in <module>
    from . import errors
  File "/Users/xxxx/personal/sandbox/lib/python3.8/site-packages/acsylla/errors.py", line 1, in <module>
    from acsylla._cython.cyacsylla import (
ImportError: dlopen(/Users/xxxx/personal/sandbox/lib/python3.8/site-packages/acsylla/_cython/cyacsylla.cpython-38-darwin.so, 2): Library not loaded: /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
  Referenced from: /Users/xxxx/personal/sandbox/lib/python3.8/site-packages/acsylla/_cython/cyacsylla.cpython-38-darwin.so
  Reason: image not found
```

**Comment by dimaqq** [comment]
It's done then, isn't it?

**Comment by whiteluna** [comment]
@dimaqq yes done, but I don't remember if these changes were in the latest build.

**Comment by whiteluna** [comment]
@dimaqq can you test this If you have some time and clean mac?

**Comment by dimaqq** [comment]
```command
(test-acsylla) ~ > pip install acsylla
...
Successfully installed acsylla-0.1.7a0

(test-acsylla) ~ > python -m acsylla
Traceback (most recent call last):
...
    from acsylla._cython.cyacsylla import CassErrorLibBadParams
ImportError: dlopen(/...my..venc.../site-packages/acsylla/_cython/cyacsylla.cpython-39-darwin.so, 0x0002): Library not loaded: /usr/local/opt/libuv/lib/libuv.1.dylib
  Referenced from: /...my..venv.../site-packages/acsylla/_cython/cyacsylla.cpython-39-darwin.so
  Reason: tried: '/usr/local/opt/libuv/lib/libuv.1.dylib' (no such file), '/usr/lib/libuv.1.dylib' (no such file)
```

**Comment by whiteluna** [comment]
Thanks, I think this is not last build

**Comment by whiteluna** [comment]
I mean without this last commit 
https://github.com/acsylla/acsylla/commit/2b9db3aa4d1df2c0e544e6b33c802d6a4fdc7ed1

**Comment by whiteluna** [comment]
@pfreixes can you make build with latest master?

**Comment by whiteluna** [comment]
As I see new release 0.1.8b0 looks like good

```
% pip install acsylla                                                              
Collecting acsylla
  Using cached acsylla-0.1.8b0-cp39-cp39-macosx_10_15_x86_64.whl (3.7 MB)
Installing collected packages: acsylla
Successfully installed acsylla-0.1.8b0

% otool -L lib/python3.9/site-packages/acsylla/_cython/cyacsylla.cpython-39-darwin.so
lib/python3.9/site-packages/acsylla/_cython/cyacsylla.cpython-39-darwin.so:
        /usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
        /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1200.3.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.0.0)
```

**Comment by dimaqq** [comment]
I'm recently macless, leaving this in your care.

**Comment by pfreixes** [comment]
Closing this as done
